CREATE TABLE Users(
    ID SERIAL PRIMARY KEY,
    LOGIN  VARCHAR(64) UNIQUE NOT NULL,
    PASS VARCHAR(64) NOT NULL
)

CREATE TABLE Chats(
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(64) NOT NULL
)

CREATE TABLE UsersChats(
    USER_ID INTEGER NOT NULL REFERENCES USERS(ID),
    CHAT_ID SERIAL NOT NULL REFERENCES Chats(ID),
    PRIMARY KEY(USER_ID, CHAT_ID)
)

CREATE TABLE ChatsMessages(
    ID SERIAL NOT NULL,
    CHAT_ID INTEGER NOT NULL REFERENCES Chats(ID),
    USER_ID INTEGER NOT NULL REFERENCES USERS(ID),
    IS_FILE boolean NOT NULL DEFAULT FALSE,
    MESSAGE text NOT NULL,
    READED_AT timestamp DEFAULT '1001-01-01',
    posted_at timestamp default NOW()
    PRIMARY KEY(ID, CHAT_ID)
)